server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: "music-query-service"
  profiles:
    active: "dev"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/music
#    username: root
#    password: password
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/music
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true


eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    registry-fetch-interval-seconds: 10

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"