server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: "music-query-service"
  profiles:
    active: "dev"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
  security:
    oauth2:
      client:
        registration:
          test:
            authorization-grant-type: password
            client-id: cqrsClient
            client-secret: secret
        provider:
          test:
            token-uri: http://oauth2-server:8084/oauth/token
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/music
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    stream:
      bindings:
        userProducer-out-0:
          destination: users
          group: userGroup
      rabbit:
        bindings:
          consumer:
            userOperationInputChannel:
                autoBindDlq: true
                republishToDlq: true
      default-binder: rabbit




eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    registry-fetch-interval-seconds: 10

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

user-query-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082
    ServerListRefreshInterval: 15000



---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"