server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: "music-query-service"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    function:
      definition: sendNeo4j
    circuitbreaker:
      resilience4j:
        enabled: true
    stream:
        bindings:
          sendNeo4j-in-0:
            destination: music-topic
            group: processor
          sendNeo4j-out-0:
            destination: music-topic-out

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "kubernetes"
  data:
    mongodb:
      uri: mongodb://mongosts-0.mongodb-service:27017,mongosts-1.mongodb-service:27017,mongosts-2.mongodb-service:27017/music?replicaSet=rs0
  r2dbc:
    url: r2dbc:mysql://mysql-0.mysql:3306/music
    username: root
    password: password
  rabbitmq:
    host: rabbitmq-cluster
    port: 5672
    username: KX68gCZyPKjI-_XmhySFvn2Mj6ZuD4GH
    password: kd7-EbebbC2RxmE1OFaVF2s4mRRApHLm
    virtual-host: /

axon:
  axonserver:
    servers: axonserver-0.axonserver


---

spring:
  config:
    activate:
      on-profile: "dev"
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music
    username: root
    password: password
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
---

spring:
  config:
    activate:
      on-profile: "prod"