version: '2'
services:
#  discovery-service:
#    container_name: discovery-service
#    hostname: discovery-service
#    build:
#      context: ./discovery-service/
#      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"
#    networks:
#      - cqrs-es
  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    ports:
      - "8065:8065"
    command: --spring.profiles.active=docker
    depends_on:
      - discovery-service
    networks:
      - cqrs-es
networks:
  cqrs-es:
    external: true