server:
  port: 8065

spring:
  application:
    name: "api-gateway"
  profiles:
    active: "dev"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      routes:
        - id: 'user-command-service'
          uri: lb://user-command-service
          predicates:
              - Path=/user-command-service/**
          filters:
            - RewritePath=/user-command-service/(?<path>.*), /$\{path}
        - id: 'user-query-service'
          uri: lb://user-query-service
          predicates:
            - Path=/user-query-service/**
          filters:
            - RewritePath=/user-query-service/(?<path>.*), /$\{path}
        - id: 'music-command-service'
          uri: lb://music-command-service
          predicates:
            - Path=/music-command-service/**
          filters:
            - RewritePath=/music-command-service/(?<path>.*), /$\{path}
        - id: 'user-query-service'
          uri: lb://music-query-service
          predicates:
            - Path=/music-query-service/**
          filters:
            - RewritePath=/music-query-service/(?<path>.*), /$\{path}


logging:
  level:
    root: INFO
    org.springframework.*: INFO

management:
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles}
    export:
      prometheus:
        descriptions: true
        enabled: true
        step: 1m
        pushgateway:
          base-url: localhost:9091
          enabled: true
          job: ${spring.application.name}
          push-rate: 20m
          shutdown-operation: push


---
spring:
  config:
    activate:
      on-profile: "docker"



---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"