# spring
server:
  port: 8084

  # mongodb
spring:
  application:
    name: "oauth2-server"

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
   oauth2:
     client:
       client-id: cqrsClient
       client-secret: secret
       signing-key:  cqrsSigningKey
       token-validity-seconds: 99999999
       refresh-token-validity-seconds: 1500

---

spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  data:
    mongodb:
      uri: mongodb://mongosts-0.mongodb-service:27017,mongosts-1.mongodb-service:27017,mongosts-2.mongodb-service:27017/user?replicaSet=rs0

axon:
  axonserver:
    servers: axonserver-0.axonserver

---

spring:
  config:
    activate:
      on-profile: "dev"
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
---

spring:
  config:
    activate:
      on-profile: "prod"