# spring
server:
  port: 8084

  # mongodb
spring:
  application:
    name: "oauth2-server"
  profiles:
    active: "dev"
  data :
    mongodb:
       host: localhost
       port: 27017
       database: user
 cloud:
   kubernetes:
     discovery:
       all-namespaces: true


management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
   oauth2:
     client:
       client-id: cqrsClient
       client-secret: secret
       signing-key:  cqrsSigningKey
       token-validity-seconds: 99999999
       refresh-token-validity-seconds: 1500


---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"