server:
  port: 8081

spring:
  application:
    name: "user-command-service"
  profiles:
    active: "dev"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"