server:
  port: 8051
  error:
    include-message: always
    include-binding-errors: always


spring:
  application:
    name: "reco-query-service"
  cloud:
    function:
      definition: onReceive
    stream:
      bindings:
        onReceive-in-0:
          destination: music-topic-out
          group: consumer




management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  neo4j:
    uri: neo4j://neo4j-release-0.neo4j-release:7687
    authentication:
      username: neo4j
      password: password
  rabbitmq:
    host: rabbitmq-cluster
    port: 5672
    username: KX68gCZyPKjI-_XmhySFvn2Mj6ZuD4GH
    password: kd7-EbebbC2RxmE1OFaVF2s4mRRApHLm
    virtual-host: /

axon:
  axonserver:
    servers: axonserver-0.axonserver


---

spring:
  config:
    activate:
      on-profile: "dev"
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /



axon:
  serializer:
    messages: jackson
    events: jackson
    general: jackson
---

spring:
  config:
    activate:
      on-profile: "prod"