server:
  port: 8051
  error:
    include-message: always
    include-binding-errors: always


spring:
  application:
    name: "reco-query-service"
  profiles:
    active: "dev"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    function:
      definition: onReceive
    stream:
      bindings:
        onReceive-in-0:
          destination: music-topic-out
          group: consumer
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password



management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey



---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"