apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-command-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-command-deployment
  template:
    metadata:
      labels:
        app: user-command-deployment
    spec:
      containers:
        - name: user-command-deployment-app
          image: user-command-api
          ports:
            - containerPort: 8081
          imagePullPolicy: Never