apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-query-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-query-deployment
  template:
    metadata:
      labels:
        app: music-query-deployment
    spec:
      containers:
        - name: music-query-deployment-app
          image: music-query-api
          ports:
            - containerPort: 8092
          imagePullPolicy: Never