server:
  port: 8091

spring:
  application:
    name: "music-command-service"
  profiles:
    active: "dev"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music
    username: root
    password: password
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true


management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "prod"