server:
  port: 8091

spring:
  application:
    name: "music-command-service"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true


management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


security:
  oauth2:
    resource:
      jwt:
        key-value: cqrsSigningKey

---

spring:
  config:
    activate:
      on-profile: "kubernetes"
  data:
    mongodb:
      uri: mongodb://mongosts-0.mongodb-service:27017,mongosts-1.mongodb-service:27017,mongosts-2.mongodb-service:27017/music?replicaSet=rs0
  r2dbc:
    url: r2dbc:mysql://mysql-0.mysql:3306/music
    username: root
    password: password



axon:
  axonserver:
    servers: axonserver-0.axonserver

---

spring:
  config:
    activate:
      on-profile: "dev"
  data:
    mongodb:
      uri: mongodb://localhost:27017/music
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music
    username: root
    password: password

---

spring:
  config:
    activate:
      on-profile: "prod"